# redefine PATH completely
PATH=/usr/sbin:/usr/bin:/sbin:/bin
PATH=/usr/local/sbin:/usr/local/bin:$PATH
PATH=/usr/local/opt/zplug/bin:$PATH

# split this into a conditional
PATH=/usr/local/opt/vim/bin:$PATH
PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
PATH=/usr/local/opt/gnu-sed/libexec/gnubin:$PATH

PATH=$HOME/bin:$PATH
PATH="$HOME/.local/bin:$PATH"
export PATH

# I prefer vim for quick editing
export EDITOR=vim

# configure LESS
export PAGER=less
# X: don't clear screen 
# F: quit if one screen is enough
# S: don't truncate lines
export LESS="-XFS"

export GOKU_EDN_CONFIG_FILE="$HOME/.config/karabiner/karabiner.edn"

if [[ -f $HOME/.zshenv.local.zsh ]]; then
  source "$HOME/.zshenv.local.zsh"
fi
